---
    name: Test Secrets Manager Action
    
    on:
      workflow_dispatch:
        inputs:    
          env:
            description: "Environment to pull secrets from"
            required: true
            type: string
    
    jobs:
      tests:
        defaults:
          run:
            shell: bash

        strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-20.04, ubuntu-22.04]

        runs-on: ${{ matrix.os }}
        name: Tests - ${{ matrix.os }}
        steps:

          - name: Retrieve secrets
            uses: bitwarden/sm-action@e6f913bdf91089a20db136dc78eb92d7502a4be8 # custom ver
            with:
              access_token: ${{ secrets.BWS_ACCESS_TOKEN }}
              base_url: ${{ inputs.env }}
              secrets: |
                b4f37a29-a0e0-423e-b283-afbd010ca70a > GIGACHAD
